help:
	@grep '####' Makefile | grep -v grep | sed -e 's/####//'

cart: #### setup cart component
	@bash components/cart.sh

catalogue: ####  setup catalogue component
	@bash compnents/catalogue.sh

shipping: #### setup shipping component
	@bash components/shipping.sh

frontend: #### setup frontend component
	@bash components/frontend.sh

payment: #### setup payment component
	@bash components/payment.sh

mongodb: #### setup mongodb component
	@bash components/mongodb.sh

mysql: #### setup mysql component
	@bash components/mysql.sh

redis: #### setup redis component
	@bash components/redis.sh

rabbitmq: #### setup rabbitmq component
	@bash components/rabbitmq.sh

user: #### setup user component
	@bash components/user.sh
